export let Tips = {
	Ok: '完成',
	NetworkError: "网络错误",
	ServerFailure: "服务器故障",
	PermissionDenied: "权限不足",
	TokenExpires: "登陆过期，请重新登陆",
	PwdTooShort: "密码大于八位",
	UidIllegal: "账号为数字且大于八位",
	PwdWrong: "账号或密码错误",
	UidNotExist: "账号不存在",
	UnknownError: "未知错误",
	NoStudent: "未设置学号与密码",
	WhutPwdWrong: "教务处密码可能错误",
	WhutServerCrashed: "教务处可能已崩溃",
	LoginSuccess: "登陆成功",
	Landing: '正在登陆...',
	PwdIsEmpty: '密码不可为空',
	UidIsEmpty: '账号不可为空',
}
